# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Trevor Bonjour
author:
  name: Trevor Bonjour
  email: tbonjour@purdue.edu

description: >- # this means to ignore newlines until "baseurl:"
  A personal blog and a public journal.
# about my PhD. Topics include but are not
# limited to: Reinforcement Learning, Machine Learning, Aritificial Intelligence, Causal Inference,
# Philosophy of Science.   
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://trevorbonjour.me" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  tbonjour
minima:
  social_links:
    github: tbonjour
    linkedin: trevor-bonjour
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

#Set permalink. Permalinks are the output path for your pages, posts, or collections.
permalink: /:categories/:title/


# Set show_excerpts: true to display posts’ excerpts on the home page.
# show_excerpts: true

# Build settings
theme: minima
# theme: minimal-mistakes-jekyll # NOT WORKING FOR SOME REASON
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
